### ISSUE TITLE
checked.cache file size

### ISSUE THREAD

**Issue by lswamy** [vqmod/vqmod#117]
During a recent dos attack, the checked.cache file size grew to over 100MB causing an allowed memory size exhausted fatal error in vqmod.php.

What causes the size of this file to grow ?

**Comment by JAY6390** [comment]
Unless you have some kind of recursive file structure, I wouldn't expect that to happen. It's just a list of files that have previously been checked to see if they need any modifications applied, and if so add them. 100MB would be a huge number of files since it's just a plain text list. Do you have a copy of the file to see what files were being checked?

**Comment by lswamy** [comment]
I deleted the file but the new checked.cache shows what the issue is.
I have a document root in /data/www/mysite/htdocs
And composer one level up, so theres a vendor folder at /data/www/mysite/vendor
I supposed this might be considered a recursive file structure ?

[checked.cache.txt](https://github.com/vqmod/vqmod/files/1197406/checked.cache.txt)

**Comment by JAY6390** [comment]
Whatever is running `/data/www/mysite/vendor/autoload.php` through the modCheck appears to be the issue. that shouldn't be going through it at all as that's not a file path that should even be accessed. You need to find what's adding that, and remove it. Your checked.cache has 323 instances of the above file (there shouldn't be more than one). Also notice it has the full path not the relative path, which is why it's adding multiple times

**Comment by lswamy** [comment]
I believe opencart is loading that autoload file in system/startup.php

// Autoloader
if (file_exists(DIR_SYSTEM . '../../vendor/autoload.php')) {
	require_once(DIR_SYSTEM . '../../vendor/autoload.php');
}
I am on OpenCart v2.2

**Comment by JAY6390** [comment]
ah, but you've moved it outside of your htdocs correct?

**Comment by JAY6390** [comment]
In order for VQMod to function, any files it modifies need to be inside the document root (the same directory the `vqmod` directory itself is in). This is because VQMod uses relative paths in all of the files. It is not possible to keep that there. I would recommend putting the vendor directory inside htdocs again. I'm assuming you've moved it outside for security. In this instance, you'll need to use .htaccess if you're on apache or the relevant config file for your nginx etc to restrict access to that directory

Kind regards
Jay

**Comment by lswamy** [comment]
I didn't move the vendor directory, that is how it is configured in the default OpenCart 2.2 and 2.3.
The composer.json file is located outside the upload directory. 

This is clearly a bug, since it has been corrected in the latest 3.0 release, by moving the vendor directory under storage and updating startup.php to point to the new location.

Thanks for your quick responses.

**Comment by JAY6390** [comment]
Hmm so it is. Sorry about that -  never seen or noticed that before. As I say, this isn't something VQMod can actually correct since it's outside of it's scope. I'd still recommend moving the vendor directory into htdocs and securing with .htaccess etc. You'll also need to edit the `system/startup.php` file and remove one of the `../` parts from each of the two lines referencing the autoloader

```
// Autoloader
if (file_exists(DIR_SYSTEM . '../vendor/autoload.php')) {
	require_once(DIR_SYSTEM . '../vendor/autoload.php');
}
```

Kind regards
Jay

**Comment by nichinu** [comment]
i have the same problem. I am using latest vqmod and opencart 3.0.2. Any solution??

**Comment by ckeilitz** [comment]
Running OC 3.0.2.0 and vqmod 2.6.3 and having the same problem. I moved the ocartdata into the public_html folder, but still having issues with duplicate entries in the checked.cache file and it growing out of control and eventually bringing OpenCart to its knees - causing a Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /.../public_html/store/vqmod/vqmod.php on line 168.  

Here are some of the duplicate entries...any help, suggestions would be greatly appreciated. By the way, as a workaround, I'm truncating the checked.cache file nightly, but given how fast it is growing I am going to have to increase the truncation to 2, 3 times a day. 

/home/hairxa5/public_html/ocartdata/storage/vendor/autoload.php
/home/hairxa5/public_html/ocartdata/storage/modification/system/library/cart/cart.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/startup/seo_url.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/product/search.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/model/catalog/product.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/column_left.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/model/design/layout.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/column_right.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/content_top.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/content_bottom.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/footer.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/header.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/search.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/cart.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/language/en-gb/common/cart.php
/home/hairxa5/public_html/ocartdata/storage/modification/catalog/controller/common/menu.php

**Comment by JAY6390** [comment]
@ckeilitz is your store in the ocartdata folder too? Moving the storage folder into the same directory as VQMod's folder fixes this for me immediately. You appear to have an ocartdata folder and a store folder?

**Comment by ckeilitz** [comment]
Thanks for the quick response @JAY6390! vqmod is in the store directory.  The ocartdata is in the public_html, document root directory.  Currently the structure looks like this:
   public_html/store/
   public_html/store/vqmod
   public_html/ocartdata

Are you suggesting this structure?
   public_html/store/
   public_html/store/vqmod
   public_html/store/ocartdata

If that's all I need to do, that's a quick fix!

**Comment by ckeilitz** [comment]
I made the change @JAY6390 and it seems to have fixed it!  I'll monitor it closely, but that was too easy.  Simply moving the ocartdata/storage folder into the same folder as the vqmod....interesting.  Do you know why this is the case, why does that fix the problem?

**Comment by JAY6390** [comment]
@ckeilitz I'm assuming that "ocartdata" is a rename of the "system" directory. If that's the case, yes it needs to be in your store directory along with the vqmod directory

**Comment by MarbleMark** [comment]
I'm still having the problem.  I have to throw out my checked.cache file every day.  My directory structure is this:
public_html/store/system/
public_html/store/vqmod/

From config.php:
define('DIR_STORAGE', '/home/mysite/public_html/storage/');

From admin/config.php:
define('DIR_STORAGE', '/home/mysite/public_html/storage/');

Among others, these files are constantly being added to the cache:

/home/mysite/public_html/storage/modification/system/library/cart/cart.php
/home/mysite/public_html/storage/modification/catalog/controller/startup/seo_url.php
/home/mysite/public_html/storage/modification/catalog/controller/product/product.php
/home/mysite/public_html/storage/vendor/autoload.php
/home/mysite/public_html/storage/modification/system/library/cart/cart.php
/home/mysite/public_html/storage/modification/catalog/controller/startup/seo_url.php
/home/mysite/public_html/storage/modification/catalog/model/catalog/product.php
/home/mysite/public_html/storage/vendor/autoload.php
/home/mysite/public_html/storage/modification/system/library/cart/cart.php
/home/mysite/public_html/storage/modification/catalog/controller/startup/seo_url.php
/home/mysite/public_html/storage/modification/catalog/model/catalog/product.php
/home/mysite/public_html/storage/vendor/autoload.php
/home/mysite/public_html/storage/modification/system/library/cart/cart.php
/home/mysite/public_html/storage/modification/catalog/controller/startup/seo_url.php
/home/mysite/public_html/storage/modification/catalog/model/catalog/product.php

Please advise, thanks.

**Comment by MarbleMark** [comment]
I see that you released a new version over the weekend.  I'll try that and let you know.

**Comment by MarbleMark** [comment]
I'm really confused.  The version on my store shows this:
	public static $_vqversion = '2.6.2';						// Current version number

I downloaded the latest version, thinking it was from June 23, 2018.  It contains this:
	public static $_vqversion = '2.6.2';						// Current version number

The zip file was labeled this:
vqmod-2.6.3-opencart.zip

So I think I'm on the latest version, and it's just mislabeled in the vqmod.php file.  I'm back to the growing cache problem.

**Comment by qphoria** [comment]
2.6.3 was only the version of the vqmod_opencart.xml file.. the core vqmod code is 2.6.2

**Comment by ckeilitz** [comment]
I had the same problem Mark. I also did tried the fix, what you did, and
put the storage directory in the public_html directory and it didn't work
for me.  However, I finally fixed it by putting the storage directory at
the same level as the vqmod directory.  Mine looks something like this:

/home/mysite/public_html/store
/home/mysite/public_html/store/vqmod
/home/mysite/public_html/store/storage

From config.php:
define('DIR_STORAGE', '/home/mysite/public_html/store/storage/');

From admin/config.php:
define('DIR_STORAGE', '/home/mysite/public_html/store/storage/');
Chris

**Comment by MarbleMark** [comment]
I moved the storage directory into the vqmod and threw out the checked.cache file.  So far, it doesn't look like it is getting any duplicate entries.

Thanks for the quick help, guys.

**Comment by Gadgetroid** [comment]
Quite confusing. [The solution is a loop.](https://github.com/vqmod/vqmod/issues/135)

**Comment by AbdelReheem** [comment]
@JAY6390  Was having same issue and it was like nightmares for 10 days as my server crashed with out of memory for about 7 time and lost a lot of orders and customer, until I figured out the unlimited increasing in checked.cache by my self and I was lucky to figure it and now i have to delete it manually each day !

So I'll apply your solution now and really thanks for adding and writing this solution here.

Just one issue which is the security as Storage contain downloads folder so how I can block accessing the storage folder in the .htaccess or any other solution to prevent direct access to it. this will be highly appreciated.

**Comment by AbdelReheem** [comment]
@JAY6390 Small update I added .htaccess inside the storage folder contain on deny from all.

So is that an optimal solution, any suggestions.

**Comment by qphoria** [comment]
@AbdelReheem your solution is a perfectly fine solution. Really we only care about the "modifications" folder, so a better idea would be to leave the storage folder there but move the "modification" folder back under the root path, back under "system" ideally. So you can leave storage alone but update your config.php and admin/config.php files
to simply change
`define('DIR_MODIFICATION', DIR_STORAGE . 'modification/');`
to
`define('DIR_MODIFICATION', DIR_SYSTEM . 'modification/');`
Then you can leave everything else alone.

Make a modification folder under the system directory then simply hit refresh in the Admin->Extensions->Modifications page to reload all your ocmods in the new path and that should do it.

**Comment by AbdelReheem** [comment]
@qphoria Perfect Idea 🥇

**Comment by AbdelReheem** [comment]
@qphoria for somehow it didn't work for me as I'm using a customized theme - Modification refreshed and no error but still give me please refresh modification on front-end, So returned back to fist solution.

**Comment by qphoria** [comment]
Hmm did you change both admin/config.php and config.php? I did it on my demo site and it seems to be working fine. Haven't tried it with Journal though so I'll see if I can try that. But can't think of any reason it shouldn't work.

**Comment by AbdelReheem** [comment]
@qphoria Yes I'm sure that i change it in both confg file. don't know why it didn't work even the folders inside modification not regenerated and no cache file generated so look like not Journal theme only.

**Comment by cepcemuh** [comment]
Hi guys, so finally what's the solution? I think I tried everything mentioned on this website but nothing helped me... So what's your solution? Thank you. I really have a headache because of that and I have to manually delete checked.cache every day.

**Comment by AbdelReheem** [comment]
@cepcemuh to cut it short and save your time and effort 
1- Move Storage back under public_html on the same level of vqmod folder.
2- and change the paths to the new storage paths in both config file.

**Comment by cepcemuh** [comment]
> @cepcemuh to cut it short and save your time and effort
> 1- Move Storage back under public_html on the same level of vqmod folder.
> 2- and change the paths to the new storage paths in both config file.

Hey @AbdelReheem , thanks for your reply. I saw all of your answers here and tried but it broke my store and I had to restore a beckup. I tried to move ocartdata but with no success. The only thing I didn't try is this one #155 . What about it? Thanks.

**Comment by AbdelReheem** [comment]
@cepcemuh ah okay, It worked for me. please double check the storage paths in both config file

also you can try the other solution [#155](https://github.com/vqmod/vqmod/pull/155),

**Comment by cepcemuh** [comment]
@AbdelReheem I will try one more time your suggestion as well. So in config files, I have to change only these DIR_STORAGE paths, right?

**Comment by samaneh68** [comment]
I also had this problem. I read your comments.
File transfer storage solves the problem but creates security problems for the site.
I changed my file Vqmod.php according to the following file.
My problem was completely solved.
You can also try!
[vqmod.txt](https://github.com/vqmod/vqmod/files/6437996/vqmod.txt)

**Comment by qphoria** [comment]
It's already been fixed in the main release for the past couple years now so no need to add the fix manually. Just update to the latest version

**Comment by e-ticaretuzman** [comment]
Use cron command on cpanel or plesk panel. Automatically delete at certain time intervals.

create: a file save; clear.php
write to file:
```
<?php
unlink("../public_html/vqmod/checked.cache");
echo "vqMod Cache File checked.cache deleted successfully.";
?>
```
Cpanel & Plesk Panels
Set it, Cron Time Command:
php -q /home/yourfolderway/public_html/clear.php
Set :
*/5  *  *  *  *
e-ticaretuzman 

**Türkçe :**
cpanel yada plesk panel üzerinde cron komutu kullanın. Belirli zaman aralıkları ile otomatik silsin. 

oluşturun: clear.php
dosyaya yazın : 
```
<?php
unlink("../public_html/vqmod/checked.cache");
echo "vqMod Cache Dosyası checked.cache başarıyla silindi.";
?>
```
Cpanel & Plesk Panelden
Ayarlayın, Cron Zamanlı Komut : 
php -q /home/yourfolderway/public_html/clear.php
Ayarlayın : 
*/5	*	 *	 *	 *

e-ticaretuzman
